spring:
  datasource:
    url: jdbc:mysql://database-2.cjl4mgclqtca.ap-northeast-2.rds.amazonaws.com:3306/farmtest
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      max-lifetime: 17

  jpa:
    generate-ddl: true
    hibernate: # create: drop-create
      ddl-auto: update
      show-sql: true
  #      naming:
  #        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto:
    stack:
      auto: false


aws:
  s3:
    presigned-url-expire-millisecond: 3600000
    region: ap-northeast-2

farmart:
  project:
    document:
      bucket: ${AWS_S3_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  use-fqn: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    version: 3.0.0
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match:
    - /v1/**
    #- /test/**